version: "3.7"

services:
    config-server:
        build:
            context: ../
            dockerfile: docker/Dockerfile.server
        image: config-server:latest
#        expose:
#            - 8888
        ports:
            - 8888:8888
        networks:
            - spring-cloud-network
        volumes:
            - spring-cloud-config-repo:/config-repo
        depends_on:
            - config-repo

    config-repo:
        build:
            context: ../
            dockerfile: docker/Dockerfile.repo
        image: config-repo:latest
        volumes:
            - spring-cloud-config-repo:/config-repo

    config-client:
        build:
            context: ../
            dockerfile: docker/Dockerfile.client
        image: config-client:latest
        entrypoint: /config-client-entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-server:8888"}}}}'
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
        depends_on:
            - config-server

networks:
    spring-cloud-network:

volumes:
    spring-cloud-config-repo:
